name: Generate Animation

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install libs
        run: pip install pillow requests

      - name: Run script
        run: python generate.py

      - name: Debug files
        run: ls -l

      - name: Commit GIF
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add animation.gif || echo "no file"
          git commit -m "update gif" || echo "no changes"
          git push
